#ifndef AI_MSFS_FILEDATA_INCLUDED
#define AI_MSFS_FILEDATA_INCLUDED

namespace Assimp {
namespace MSFS {
#define AI_MSFS_FOURCC_RIFF AI_MAKE_MAGIC("RIFF")
#define AI_MSFS_FOURCC_MDL8 AI_MAKE_MAGIC("MDL8")
#define AI_MSFS_FOURCC_MDLH AI_MAKE_MAGIC("MDLH")
#define AI_MSFS_FOURCC_DICT AI_MAKE_MAGIC("DICT")
#define AI_MSFS_FOURCC_BGL AI_MAKE_MAGIC("BGL ")
}
}

#endif // AI_MSFSFILEDATA_INCLUDED
